name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "14.15"

      - name: Install and build
        run: |
          npm install
          npm run build
          cp CNAME ./build
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}